### ISSUE TITLE
Installation needs an update

### ISSUE THREAD

**Issue by nachtgold** [greenmoss/PyWavefront#10]
When I run `pip install PyWavefront` I got the following message:

```
Collecting PyWavefront
  Downloading PyWavefront-0.1.2.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "c:\users\kai\appdata\local\temp\pip-build-l2skpl\PyWavefront\setup.py", line 12, in <module>
        long_description=open('README.md').read(),
    IOError: [Errno 2] No such file or directory: 'README.md'
```

To workaround it, I replaced the long description with an empty string.

**Comment by greenmoss** [comment]
Please try again with 0.1.3, which I just uploaded.

**Comment by nachtgold** [comment]
With 0.1.3 I got the same error and when I manually download the tar from https://pypi.python.org/pypi/PyWavefront/0.1.3, the readme isn't included.
