### ISSUE TITLE
import .obj without material file

### ISSUE THREAD

**Issue by rapha411** [greenmoss/PyWavefront#16]
Hi,

I am trying to run a simple example looking like this:

import pywavefront
mesh = pywavefront.Wavefront('path_to_obj/test.obj')
  
Running this I get the following error that I'm not able to solve:

  File "/Library/Python/2.7/site-packages/pywavefront/__init__.py", line 53, in __init__
    ObjParser(self, self.file_name)
  File "/Library/Python/2.7/site-packages/pywavefront/__init__.py", line 75, in __init__
    self.read_file(file_name)
  File "/Library/Python/2.7/site-packages/pywavefront/parser.py", line 44, in read_file
    self.parse(line, dir=os.path.dirname(file_name))
  File "/Library/Python/2.7/site-packages/pywavefront/parser.py", line 67, in parse
    parse_function(args)
  File "/Library/Python/2.7/site-packages/pywavefront/__init__.py", line 120, in parse_f
    self.material = material.Material()
TypeError: __init__() takes exactly 2 arguments (1 given)

Is there a way to load .obj files without a material file?

**Comment by xiaozai** [comment]
Hi,  do you solve this problem? I have the same question, Thanks

**Comment by muha321** [comment]
Hi xiaozai,

unfortunately I could not, so eventually I made my own implementation to import OBJs. You can find it here:  https://github.com/muha321/ShapeDNA
However, I just wanted to quickly implement an idea, so don't expect much :)

**Comment by Marxlp** [comment]
This is due to the `material.Material` __init__ function

> class Material(object): 
>     def __init__(self, name): 
>         self.name = name 
>         self.diffuse = [.8, .8, .8, 1.] 
>         self.ambient = [.2, .2, .2, 1.] 
>         self.specular = [0., 0., 0., 1.] 
>         self.emissive = [0., 0., 0., 1.] 
>         self.shininess = 0. 
>         self.texture = None 
>  
>         # Interleaved array of floats in GL_T2F_N3F_V3F format 
>         self.vertices = [] 
>         self.gl_floats = None 

You can see that it need another argument `name`, so it's a bug @greenmoss. 
You can solve this just set the `name` default value as `None` like 
>  # above lines
>      def __init__(self,name=None)
>  # below lines

**Comment by greenmoss** [comment]
@Marxlp looks reasonable; can you submit a PR please?

**Comment by Marxlp** [comment]
Yes, I have made a pull request.

**Comment by greenmoss** [comment]
PR merged. Note for me:

- update version, history, and push to pypi

**Comment by greenmoss** [comment]
Haha yeah it would be good to automate the releases and tickets.
