### ISSUE TITLE
Attribute Error

### ISSUE THREAD

**Issue by thecyclone** [greenmoss/PyWavefront#17]
AttributeError: 'ObjParser' object has no attribute 'parse_g

**Comment by frlnx** [comment]
Commenting out lines that start with g in the obj file will solve the issue. The library does not support this feature yet.

**Comment by matthew-carpenter** [comment]
You can also add a stub in the __init__.py file. That will load it without commenting it out.

**Comment by einarf** [comment]
Wasn't this issue fixed when the `strict` attribute was added?

**Comment by greenmoss** [comment]
Yep, thanks for the update!
