### ISSUE TITLE
Pyglet dependency should be optional/extra

### ISSUE THREAD

**Issue by SergioRAgostinho** [greenmoss/PyWavefront#24]
As you state in the readme.md

> This python module allows you to read Wavefront 3D object files (something.obj and something.mtl) and use them as Python objects. Currently Pyglet is required to render and display these objects.

Objective: create python objects with obj file data. pyglet is totally optional and your package should reflect this.

https://github.com/greenmoss/PyWavefront/blob/4e47c1561b0d0bc3089c695ac151513f58eebe4d/pywavefront/__init__.py#L35
Importing pyglet at this level makes it required. It should only be imported when actually needed.

**Comment by greenmoss** [comment]
Agreed, would be great to break out pyglet dependency.

**Comment by einarf** [comment]
Definitely. The pyglet dependency does create issues in some instances.
