### ISSUE TITLE
Installation failed

### ISSUE THREAD

**Issue by supermouette** [greenmoss/PyWavefront#25]
Hi !
I don't if it's the right place, to talk about this, sorry if i do wring.

I tried to installed PyWavefront on my computer (windows 10, with anaconda)
I tried both "pip install PyWavefront" and "python setup.py install"

each time I have the error : 

> Traceback (most recent call last):
>   File "setup.py", line 12, in <module>
>     long_description=open('README.md').read(),
>   File "C:\ProgramData\Anaconda3\lib\encodings\cp1252.py", line 23, in decode
>     return codecs.charmap_decode(input,self.errors,decoding_table)[0]
> UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 1741: character maps to <undefined>

So it seems like there is a wierd character in README.md
As a workaround, i deleted the ~15 lasts lignes of the README, and the installation worked, but maybe you want to fix this

**Comment by greenmoss** [comment]
Yeah, it's the accented character in one of the contributor names 😞 

The solution seems to be https://github.com/mozilla/unicode-slugify/issues/16#issuecomment-102840930

**Comment by SergioRAgostinho** [comment]
Wow. Opened a Pandora's box from inserting my name in a Readme file :cry: I never crossed my mind that the file was being saved with anything else other than utf-8.

**Comment by greenmoss** [comment]
Probably a PEBKAC problem over here. I just merged #27, but I think I'll have to do another release before pip catches up. Seems like removing the pyglet dependency is almost done, so I'll wait for that before I release.

**Comment by greenmoss** [comment]
Release 0.2.0 done, including fix
