### ISSUE TITLE
Texture coordinates without normals

### ISSUE THREAD

**Issue by einarf** [greenmoss/PyWavefront#32]
https://github.com/greenmoss/PyWavefront/blob/d05ba434f105b1144defc7357d499f725c6086b0/pywavefront/__init__.py#L111

Having normals is not really a requirement. I can make a PR removing this, but I don't know what implications with will have for the drawing in this library. (Not something I use)

**Comment by einarf** [comment]
This is also linked to #22 were the core issue is that PyWavefront is hardcoded to one vertex format.

**Comment by SergioRAgostinho** [comment]
> Having normals is not really a requirement. I can make a PR removing this, but I don't know what implications with will have for the drawing in this library. 

The "good thing" is that all the examples in this lib employ the drawing routines, so whatever changes you decide to make, you can always try to see the results immediately.

**Comment by einarf** [comment]
> The "good thing" is that all the examples in this lib employ the drawing routines, so whatever changes you decide to make, you can always try to see the results immediately.

This has no value to me, but seeing that pyglet have been part of this library for visualization I will definitely respect that. What was outlined in #22 also seems to preserve this.

Feel free to close this if #22 is renamed to something more generic related to vertex format.

**Comment by greenmoss** [comment]
I really had to do some digging to look this one up. The first iteration of this was a warning, because without normals the render showed a black screen. Ref:

https://github.com/greenmoss/PyWavefront/commit/e2347bedc92391f9c49701d9ab851f188e3a12cd#diff-c9d20f1c97263663c3302082b2179853L86

I changed it to an exception thinking it might be an error the user would otherwise miss. What is the most desirable behavior here? Should there be a warning, or nothing at all?

**Comment by einarf** [comment]
@greenmoss As mentioned in #22 we will update the pyglet drawing code so it works. We will only support the vertex formats pyglet supports with `glInterleavedArray`.

**Comment by greenmoss** [comment]
Just reading this after looking at the PR. So the updates in the PR remove the need for the normals check? If that is the case, the whole unit test can go away (it's currently just commented out).

**Comment by greenmoss** [comment]
Fixed in #38
