### ISSUE TITLE
`strict` should probably be an instance attribute instead of class attribute

### ISSUE THREAD

**Issue by einarf** [greenmoss/PyWavefront#35]
`strict` is currently a class attribute. Changing it will affect the behavior or all parsers.
I suggest making `strict` an optional parameter to `__init__` that defaults to `False`.

```python
class ObjParser(parser.Parser):
    def __init__(self, wavefront, file_name, strict=False):
        super(ObjParser, self).__init__(file_name, strict=strict)

class Parser(object):
    def __init__(self, file_name, strict=False):
        self.strict = strict
```

This way the user can be more confident as the value is configured per parser instance.

Personally I will need to have many parser instances in memory at the same time, so this is a valid concern for me. Will this affect anything I don't know about?

**Comment by einarf** [comment]
Fixed. Will make PR once my last ones are merged.

**Comment by greenmoss** [comment]
That use case makes sense.
