### ISSUE TITLE
configurable parser encoding

### ISSUE THREAD

**Issue by einarf** [greenmoss/PyWavefront#36]
Python3's `open` method opens the file using the systems encoding by default unless otherwise is specified.

> In text mode, if encoding is not specified the encoding used is platform dependent: locale.getpreferredencoding(False) is called to get the current locale encoding.

In python2's `open` seems to always use byte `str` with `US-ASCII` encoding. I've bumped into quite a few obj files containing characters outside the python 2 `str` range.

It might be a good idea to make this a bit more deterministic by passing in `utf-8` as the default encoding in the constructor and use `codecs.open` to read the files. This is slightly slower compared to reading byte strings, but will ensure the parser works in the vast majority of the cases. People who want to optimize can pass in 8 bit encodings if needed.

**Comment by einarf** [comment]
Fixed. Will make PR once my last ones are merged.

**Comment by greenmoss** [comment]
👍
