### ISSUE TITLE
Support reading .gz files

### ISSUE THREAD

**Issue by einarf** [greenmoss/PyWavefront#37]
A lot of obj files are often gzipped by default obviously because of the nature of the format and the 4:1 or higher compression rate with larger files. It would be fairly trivial to support this considering python 2 and 3 has pretty extensive support for reading and writing gzip files.

**Comment by greenmoss** [comment]
Yeah I agree, this would be really helpful.

**Comment by einarf** [comment]
Fixed in my PR.
