### ISSUE TITLE
Cannot install with pip install

### ISSUE THREAD

**Issue by John-P** [greenmoss/PyWavefront#4]
Using `pip install pywavefront` I get the following:

```
Could not find a version that satisfies the requirement pywavefront (from versions: )
No matching distribution found for pywavefront
```

**Comment by rylanchiu** [comment]
Same issue here.

**Comment by greenmoss** [comment]
Hi all, thanks for reporting this, and sorry to be so slow about responding. This should be fixed now. Please let me know if it's still not working.
