### ISSUE TITLE
PyWavefront are missing basic tags/topics on github

### ISSUE THREAD

**Issue by einarf** [greenmoss/PyWavefront#50]
PyWavefront don't have any tags/topics set here on github. It can make a difference when people seach up projects. They can be added by clicking the "Manage Topics" right under project description.

Some suggestions: python, python2, python3, wavefront, wavefront-obj, 3D, loader, opengl-library

(Sorry for the nagging!)

**Comment by greenmoss** [comment]
No worries. Thanks, I added them!
