### ISSUE TITLE
Markdown still renders incorrectly on pypi

### ISSUE THREAD

**Issue by einarf** [greenmoss/PyWavefront#56]
I think you are deploying with an old version of setuptools. You need `setuptools>=38.6.0` for it to work. 

`pip install -U setuptools` should fix it..

**Comment by greenmoss** [comment]
I'm on `39.2.0`

**Comment by greenmoss** [comment]
I wonder if there's a different command I should be using. Current is

`python setup.py sdist upload`

**Comment by einarf** [comment]
Found this article: https://dustingram.com/articles/2018/03/16/markdown-descriptions-on-pypi

I'm guessing `wheel>=0.31.0` is the issue here.

**Comment by einarf** [comment]
https://packaging.python.org/guides/tool-recommendations/

> **Packaging tool recommendations**
> * Use setuptools to define projects and create Source Distributions. [5] [6]
> * Use the bdist_wheel setuptools extension available from the wheel project to create wheels. This is especially beneficial, if your project contains binary extensions.
> * Use twine for uploading distributions to PyPI.

**Comment by greenmoss** [comment]
Hmm. I feel like there's a "testing" version of pypi somewhere that I could use. It would be great to run various tests without spamming the "real" pypi.

**Comment by einarf** [comment]
https://test.pypi.org/
https://packaging.python.org/guides/using-testpypi/

**Comment by einarf** [comment]
You have an excuse to try this again if the two PRs I added goes through 😄

**Comment by einarf** [comment]
I just tested using markdown with one of my projects. Worked out out the box as long as you ensure setuptools, twine and wheel is up to date.

**Comment by greenmoss** [comment]
Beautiful!

<img width="851" alt="screen shot 2018-07-20 at 4 18 25 pm" src="https://user-images.githubusercontent.com/134408/43023349-8d09e0ac-8c38-11e8-9004-33a7476d3784.png">

The key was to use `twine upload`.

**Comment by einarf** [comment]
Awesome 😄 

Now I can relax.
