### ISSUE TITLE
Configurable logging

### ISSUE THREAD

**Issue by einarf** [greenmoss/PyWavefront#58]
I'm reading a lot of huge files causing logs or the terminal to be cluttered with a lot of useless messages. We should make a global logger for this package `pywavefront` that can easily be configured at `info`, `warning` and `error` level.

This should not be a difficult task to complete.

**Comment by einarf** [comment]
#60 is an attempt to add basic logging

**Comment by greenmoss** [comment]
#60 merged; thanks for the report!
