### ISSUE TITLE
binary file cache of parsed scene

### ISSUE THREAD

**Issue by einarf** [greenmoss/PyWavefront#61]
Loading large scenes can be very time consuming when they are 50-300MB or even higher. It could be practical supporting dumping the raw parsed result into a ``.bin`` file as an optional feature. This would just be serializing the interleaved ``vertices`` arrays into a file in binary format with some simple structure.

Parsing the rungholt scene (http://casual-effects.com/data/index.html), often used as a benchmark scene takes about a minute. That's actually not bad for a python parser, but we can do better.

Triangles: 6.7M
Vertices: 12.3M

**Comment by einarf** [comment]
The idea is basically to just write the interleaved ``vertices`` for each material to a file using ``struct`` as binary data. Then we create a json file referencing where each buffer in the file is located. This is similar to how the GLTF format works and makes the work a lot more simpler.

```json
{
    "version": "0.1",
    "materials": [
        "matlib1.mtl",
        "matlib2.mtl"
    ],
    "vertex-data": [
        {
            "material": "default",
            "byte_offset": 0,
            "byte_length": 21344,
            "vertex_format": "V3_N3_C3_V3"
        },
        {
          .... etc ..
        }
    ]
}
```

**Comment by einarf** [comment]
Some initial tests after implementing the cache functionality:

Scene: Sponza [22M]
Load time (obj): 4.65s
Load time (cached): 0.30s ~15 x faster

Scene: Vokselia Spawn [81MB]  (http://casual-effects.com/data/index.html)
Load time (obj): 21.51s
Load time (cached): 1.97s ~11 x faster

Scene: Rungholt [276MB] (http://casual-effects.com/data/index.html)
Load time (obj): 256.92s
Load time (cached): 9.5s ~27 x faster

**Comment by greenmoss** [comment]
PR #63 merged
