### ISSUE TITLE
PyWavefront 0.4.0 was only built for Python 2

### ISSUE THREAD

**Issue by einarf** [greenmoss/PyWavefront#64]
The last release was only built for python 2 probably because it was created in a python 2 environment. It looks like you have to use the ``--universal`` flag (``python setup.py bdist_wheel --universal``) to create a py2 and py3 whl file.
https://wheel.readthedocs.io/en/stable/#defining-the-python-version

I don't think you need to release a new version since pypi do support uploading several distribution files for the same version. Worst case bump to 4.1.

I didn't really think about this because most projects for work and hobby have been python 3 only for the last couple of years, so setuptools built py3 only pacakges with bdist_wheel in python3 environment.

**Comment by einarf** [comment]
Quick test (in py3 env)

Python 3 only
```bash
$ python setup.py bdist_wheel
$ ls dist/
PyWavefront-0.3.2-py3-none-any.whl
```

Universal
```bash
$ python setup.py bdist_wheel --universal``
$ ls dist/
PyWavefront-0.3.2-py2.py3-none-any.whl
```

Note the ``py2.py3`` part.

**Comment by einarf** [comment]
Also remember to check in the version change in ``setup.py`` (can cause some trouble for people running from source)

https://github.com/greenmoss/PyWavefront/blob/2656a8b2b3cf058c1a42401cafc5e17a7d23f04a/setup.py#L3

**Comment by greenmoss** [comment]
I am getting forgetful about steps, so I put them all in `RELEASE.md` to remember. This should be good to go now, included in `0.4.1`.

**Comment by einarf** [comment]
Thanks for putting up with my nagging ❤️

**Comment by greenmoss** [comment]
No worries, I'm happy to help support.
