### ISSUE TITLE
'MaterialParser' object has no attribute 'parse_map_Ka'

### ISSUE THREAD

**Issue by riegaz** [greenmoss/PyWavefront#69]
Does anyone know why I get this error when I try to load an obj file?

**Comment by riegaz** [comment]
I just saw when doing pip install pywavefront, it installs v0.1.5. I guess this is a problem. How to install this package within anaconda?

**Comment by riegaz** [comment]
Ok, I just installed your latest version 0.4.1 and I get the exact same error.

**Comment by riegaz** [comment]
My .mtl file looks like this:

```
newmtl mat1
map_Ka mat1.png
Ks 0.2000 0.2000 0.2000
Ns 65.0000
Ns 2
Ni 1
Tf 1 1 1
illum 2
```

**Comment by einarf** [comment]
Looks like the material only reads ``map_Kd`` diffuse. ``map_Ka`` is the ambient texture map. Should not be hard to add support for that.

https://github.com/greenmoss/PyWavefront/blob/d624aae8f7d32f473f45d3605d1e13317fd75b15/pywavefront/material.py#L171-L174

It should load fine if you change ``map_ka`` to ``_map_Kd`` in your material file as a quick fix.

**Comment by greenmoss** [comment]
Merged, thanks for the report and fix!
