### ISSUE TITLE
1.0.0 was released as universal

### ISSUE THREAD

**Issue by einarf** [greenmoss/PyWavefront#79]
FYI: https://pypi.org/project/PyWavefront/#files

The current wheel is named:
```
PyWavefront-1.0.0-py2.py3-none-any.whl 
```

This will cause issues for python 2 users.

**Comment by greenmoss** [comment]
oh... have to *not* use `--universal`, right? So build command becomes

`python setup.py bdist_wheel`

Is that correct?

**Comment by einarf** [comment]
> oh... have to not use --universal, right?

Correct. When not using ``--universal`` the wheel will only be built for the python version it was created in.

**Comment by einarf** [comment]
You cannot update release on pypi, but you can delete them afaik.

**Comment by greenmoss** [comment]
If I do `1.0.1` instead of trying to fix `1.0.0`, will that be OK?

**Comment by einarf** [comment]
I think you need to delete 1.0.0 and release 1.0.1 yup

**Comment by einarf** [comment]
Also, from personal experience it will always be easier to build a version in a python 3.6+ env. If you install 3.4 from scratch for this purpuse you'll bump into way too many issues with pip and setuptools not being up to date.

**Comment by greenmoss** [comment]
Right; I'm updating the `RELEASE.md` file to reflect this

**Comment by greenmoss** [comment]
`1.0.0` deleted from pypi

**Comment by greenmoss** [comment]
Upload/release complete. Verified it's py3 only. Still waiting for pypi.org to update, but verified `1.0.1` is visible, and `1.0.0` is deleted via the admin back-end.

**Comment by einarf** [comment]
Success!

With python 2.7.15
```
$ pip install PyWavefront
Collecting PyWavefront
  Downloading https://files.pythonhosted.org/packages/f0/a3/6ca004f861af7775dd666ea1fc537a1ce90f2ae5afeac5525eb7e43a29d9/PyWavefront-0.4.2-py2.py3-none-any.whl
Installing collected packages: PyWavefront
Successfully installed PyWavefront-0.4.2
```

With python 3.7
```
$ pip install PyWavefront
Collecting PyWavefront
  Downloading https://files.pythonhosted.org/packages/cc/d0/39dad65336b592ea70530ae79b03ed7e4dea622aa7771d3b41a92953d94b/PyWavefront-1.0.1-py3-none-any.whl
Installing collected packages: PyWavefront
Successfully installed PyWavefront-1.0.1
```
