### ISSUE TITLE
How to change the code for 3 faced objects

### ISSUE THREAD

**Issue by vinaysannaiah** [greenmoss/PyWavefront#83]
I am a newbie in this field, one of my project involves face objects having only 3 faces. But I could see that all your example objects has 4 faces and this code works super fine only for tose examples. When io try the same for my obj having only 3 faces the output is not proper.

your obj has 4 faces ex:
f 2032/8314/8034 6001/2053/2053 8020/2057/2057 6034/8315/8033
f 2033/8318/8036 6033/8319/8035 6135/8320/7940 6032/8321/8037

My obj has 3 faces ex:
f 4606/4606/4606 9943/9943/9943 9944/9944/9944
f 9944/9944/9944 4603/4603/4603 4606/4606/4606

![screenshot](https://user-images.githubusercontent.com/36826364/46796325-af79be00-cd4c-11e8-8610-852ecf928c22.jpg)

Please help me chnaging the code for my obj file.

Thank you.

**Comment by einarf** [comment]
Sorry for not responding to this earlier. Did you manage to resolve this issue? It's hard to know what's wrong unless you share more details about how you draw the object.

**Comment by einarf** [comment]
Closing this one for now. Be free to respond with more details if you still need help.
